# Используем Python образ
FROM python:3.9-slim

# Устанавливаем рабочую директорию для тестов
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем сами тесты
COPY tests.py /app/

# Запускаем тесты
CMD ["python", "-m", "unittest", "tests.py"]
